# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170909_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_time', 'title']},
        ),
        migrations.AddField(
            model_name='post',
            name='viewnum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
